ControlEscolar/Controllers/AntonioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControlEscolar.Controllers
{
    public class AntonioController : Controller
    {
        // GET: Antonio
        public ActionResult Index()
        {
            return View();
        }
        [Route("Materia")]
        public ActionResult Materia()
        {
            return View();
        }
    }
}

ControlEscolar/Controllers/DanielController.cs
using ControlEscolar.Models;
using ControlEscolar.Models.Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControlEscolar.Controllers
{
    public class DanielController : Controller
    {
        // GET: Daniel
        public ActionResult Index()
        {
            List<C_Materia> lst;
            using (CursoEscolarEntities db = new CursoEscolarEntities())
            {
                lst = (from d in db.Materia
                       select new C_Materia
                       {
                           Id = d.Mat_Id,
                           Nombre = d.Mat_Nombre
                       }).ToList();
            }
            return View(lst);
        }

        public ActionResult Inscribir()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Inscribir(C_Materia model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (CursoEscolarEntities ControlEscolar = new CursoEscolarEntities())
                    {
                        var oLista = new Materia();
                        oLista.Mat_Id = model.Id;
                        oLista.Mat_Nombre = model.Nombre;
                    }
                }
                return ViewBag.model = model;
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

    }   
}

ControlEscolar/Controllers/RicardoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControlEscolar.Controllers
{
    public class RicardoController : Controller
    {
        // GET: Ricardo
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Profesores()
        {
            ViewBag.Title = "Profesores";
            return View();
        }
    }
}

ControlEscolar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <!--Barra de navegación-->
    <nav class="navbar navbar-expand-sm navbar-dark fixed-top bg-dark">
        <div class="container"> 
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @Html.ActionLink("Control Escolar", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <div class="navbar-collapse collapse" id="navbarSupportedContent">
                <ul class="nav navbar-nav mr-auto">
                    <li class="nav-item">@Html.ActionLink("Alumnos", "Index", "Alumnos", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Profesores", "Profesores", "Ricardo", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Materias", "Materia", "Antonio", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Inscripciones", "Inscribir", "Daniel", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Grupos</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item">@Html.ActionLink("Grupos", "Grupos", "Home", new { area = "" }, new { @class = "dropdown-item" })</a>
                            <a class="dropdown-item">@Html.ActionLink("Alumnos Inscritos", "AlumnosGpo", "Inscripcion", new { area = "" }, new { @class = "dropdown-item" })</a>
                        </div>
                    </li>
                    <li class="nav-item">@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("API", "Index", "Help", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>